# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: articles/:categories/:title.html

exclude: ["mvc"]
auto: true
pygments: true

# Site settings
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.peigong.net" # the base hostname & protocol for your site
# Build settings
markdown: kramdown
