[book]
authors = ["VET. 周培公"]
language = "en"
multilingual = false
src = "src"
title = "English Tour Guiding in Beijing - VET.周培公(https://pg.js.cn)"

[build]
build-dir = "../../public/guide/english-tour-guiding-in-beijing"

[output.html]
default-theme = "rust"
git-repository-url = "https://github.com/peigong/peigong.github.io"
edit-url-template = "https://github.com/peigong/peigong.github.io/edit/master/guide/{path}"
site-url = "/guide/english-tour-guiding-in-beijing/"
cname = "pg.js.cn"