[book]
authors = ["VET.PG"]
language = "en"
multilingual = false
src = "src"
title = "The Journey to the West - VET.PG(https://pg.js.cn)"

[build]
build-dir = "../../public/guide/The-Journey-to-the-West"

[output.html]
default-theme = "rust"
git-repository-url = "https://github.com/peigong/peigong.github.io"
edit-url-template = "https://github.com/peigong/peigong.github.io/edit/master/guide/{path}"
site-url = "/guide/The-Journey-to-the-West/"
cname = "pg.js.cn"